# syntax=docker/dockerfile:1
FROM ruby:2.5.7
RUN apt-get update -qq && apt-get install -y nodejs postgresql-client
WORKDIR /knowyourhizb
COPY Gemfile /knowyourhizb/Gemfile
COPY Gemfile.lock /knowyourhizb/Gemfile.lock
RUN bundle install

# Configure the main process to run when running the image
CMD ["rails", "server", "-b", "0.0.0.0"]